services:
  ollama:
    image: ollama/ollama:latest
    container_name: ollama
    restart: unless-stopped
    command: ollama run llama3.2   ## ["ollama", "run", <model_name>] 
    network_mode: host
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              device_ids: ['0', '1']
              capabilities: ["gpu"]
    ports:
      - 11434:11434
    volumes:
      - type: bind
        source: /home/docker/ollama
        target: /root/.ollama
    runtime: nvidia