version: '3.8'

services:
  ollama:
    image: ollama/ollama:latest
    container_name: ollama
    restart: unless-stopped
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              device_ids: ['0', '1']
              capabilities: ["gpu"]
    ports:
      - 11434:11434
    volumes:
      - ollama:/root/.ollama
    runtime: nvidia

volumes:
  ollama: